controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    game_state = 2
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game_state = 3
})
let projectile: Sprite = null
let game_state = 0
let nathan = sprites.create(img`
    .................ccfff..............
    ................cddbbf..............
    ...............cddbbf...............
    .........ffffffccbbcf...............
    ......fffbbbbbbbbcccff..............
    .....fbbbbbbbbbbbbbbbcfff......ccccc
    .....bcbbbbbffbcbcbbbbcccff...cdbbbc
    .....bbb1111ffbbcbcbbbcccccffcddbbc.
    .....fb11111111bcbcbbbcccccccbdbbf..
    ......fccc33c11bbbbbbcccccccccbbcf..
    .......fc131cc11bbbbccccccccffbccf..
    ........f33c1111bbbcccccbdbc..fbbcf.
    .........ff1111cbbbfdddddcc....fbbf.
    ...........ccc1fbdbbfddcc.......fbbf
    ..............ccfbdbbfc..........fff
    .................fffff..............
    `, SpriteKind.Enemy)
let aiden = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
nathan.setPosition(74, 10)
aiden.setPosition(82, 109)
controller.moveSprite(aiden)
aiden.setStayInScreen(true)
nathan.setStayInScreen(true)
game_state = 1
let textSprite = textsprite.create("Space Shooter -- Aiden")
textSprite.setPosition(75, 60)
game.onUpdate(function () {
    if (game_state == 3) {
        game.gameOver(false)
    }
})
game.onUpdateInterval(1000, function () {
    if (game_state == 2) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . 2 2 2 2 2 2 2 2 . . . . 
            . . . 2 4 4 4 5 5 4 4 4 2 2 2 . 
            . 2 2 5 5 d 4 5 5 5 4 4 4 4 2 . 
            . 2 4 5 5 5 5 d 5 5 5 4 5 4 2 2 
            . 2 4 d d 5 5 5 5 5 5 d 4 4 4 2 
            2 4 5 5 d 5 5 5 d d d 5 5 5 4 4 
            2 4 5 5 4 4 4 d 5 5 d 5 5 5 4 4 
            4 4 4 4 . . 2 4 5 5 . . 4 4 4 4 
            . . b b b b 2 4 4 2 b b b b . . 
            . b d d d d 2 4 4 2 d d d d b . 
            b d d b b b 2 4 4 2 b b b d d b 
            b d d b b b b b b b b b b d d b 
            b b d 1 1 3 1 1 d 1 d 1 1 d b b 
            . . b b d d 1 1 3 d d 1 b b . . 
            . . 2 2 4 4 4 4 4 4 4 4 2 2 . . 
            . . . 2 2 4 4 4 4 4 2 2 2 . . . 
            `, nathan, 0, 50)
        nathan.x += randint(-100, 100)
    }
})
